# Site Information
description: "邓小龙博客，致力于简单可靠的lnmp架构"
keywords: "邓小龙,lnmp,php,mysql,linux,nginx"
favicon: images/favicon.ico
rss: /atom.xml

# Site Menu
# Neet slash(/) at the end
menu:
  home: /
  # 技术: categories/technology/ 
  技术: categories/tech/

# Site Sidebar Widget
widgets:
  - recent_post
  - tagcloud
  - categories
  # - archives
  - links

# Site Friend Links
links:
  wiki: https://wiki.huimang.com/
  吴钧泽博客: https://wujunze.com/

analytics:
  baidu: aaa
  #baidu: 0a275bcf7d954b807e1db498d8e5b192

# Site Verification
verification:
  baidu: sdfd
  #baidu: 0a275bcf7d954b807e1db498d8e5b192
  #google: j5dWC85DkoAfUR50W00ewfii3X9ouH55HnyBP6oZxGE

comment:
  #disqus: dengxiaolong
  #uyan: 1507133
  gentie:
    key: e56d3daef8d44c66a2e059aea3250e3a
    token: aHR0cHM6Ly9hcGkuZ2VudGllLjE2My5jb20vcGMvbGl2ZXNjcmlwdC5odG1s
